### ISSUE TITLE
Build an interactive component for illustrating tree traversal

### ISSUE THREAD

**Issue by johno** [unifiedjs/handbook#3]
Tree traversal is a complex topic that we should explain visually. Ideally we could render a tree structure and light up active visits to illustrate depth-first/breadth-first searches and their different variants.

We can also use this to show the mdast and how `unist-util-visit` works.

**Comment by wooorm** [comment]
Oh that’s a good idea! ⚡️

**Comment by swyxio** [comment]
i've never been a fan of how babel basically allows unrestricted traversal  (so that babel plugin order both does and doesn't matter , but basically you get weird conflicts just bc of how they visit nodes)... i dont have much other AST traversal experience but maybe addressing some advice on good practices here would be nice

**Comment by wooorm** [comment]
Closing as the repo will be archived; while not interactive, there’s some more info on traversal on the unified site: https://unifiedjs.com/learn/
